// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Published     bool               `json:"published"`
}

type Processed struct {
	ID      uuid.UUID   `json:"id"`
	Content pgtype.Text `json:"content"`
}

type Test struct {
	ID      uuid.UUID   `json:"id"`
	Content pgtype.Text `json:"content"`
}
