// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, created_at, published_at, published FROM outbox
WHERE published IS FALSE
ORDER BY created_at
LIMIT 100
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO outbox(ID, EVENT_TYPE, AGGREGATE_TYPE, AGGREGATE_ID, PAYLOAD)
VALUES($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	ID            uuid.UUID `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const insertTest = `-- name: InsertTest :one
INSERT INTO test(ID, CONTENT)
VALUES ($1, $2)
RETURNING id, content
`

type InsertTestParams struct {
	ID      uuid.UUID   `json:"id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) InsertTest(ctx context.Context, arg InsertTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, insertTest, arg.ID, arg.Content)
	var i Test
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}

const setEventAsPublished = `-- name: SetEventAsPublished :exec
UPDATE outbox
SET published = TRUE, published_at = NOW()
WHERE id = $1
`

func (q *Queries) SetEventAsPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEventAsPublished, id)
	return err
}
